<?php
//
// The following items need to be changed to match the phone message system
//
// Location and URL of phone message system index and logo
$image_webhome	= '<a href="./index.php"><img src="./images/logo.png" title="b2epms" alt="logo.png" style="border: 0px solid ;" /></a>';
// Name & Description of the phone message system
$site_name	= 'b2ePMS';
$site_description = ' ::  Phone Message System';
// Url for the phone message system
$site_url = 'http://yoursite.com/b2epms/';
// Site administrators email address
$admin_email = 'admin@yoursite.com';
// Footer copyright - DON'T CHANGE THIS
$copyright = 'Powered by: <a href="http://b2epms.berlios.de">b2ePMS-1.0</a> &copy; 2005-2009<br />b2ePMS is Free Software released under the <a href="http://www.gnu.org/licenses/gpl.txt">GNU/GPL license</a>';
// XHTML compliance indicator
$xhtml_compliance = '<a href="http://validator.w3.org/check?uri=referer"><img src="./images/vxhtml10.png" alt="Valid XHTML 1.0!" height="31" width="88" style="border-style:none" /></a>';
// Open the table for the site name/description
$header_open_table1 = '<table style="text-align: left; width: 100%;" border="0" cellspacing="0" cellpadding="2"><tr><td style="width: 75%; text-align: left; vertical-align: top; font-size: x-large;">';
// Open the table for the date
$header_open_table2 = '<td style="width: 25%; text-align: right; vertical-align: middle; font-size: small;">';
// Close the table for the site name/description
$header_close_table1 = '</td>';
// Close the table for the date
$header_close_table2 = '</td></tr></table>';
// Open the table for the message display
$msg_open_table1= '<table style="text-align: left; width: 100%;" border="0" cellspacing="0" cellpadding="0"><tr><td style="width: 75%; text-align: left; vertical-align: top;">';
// Close the table for the message display
$msg_close_table1 = '</td></tr></table>';
// Open the table for the copyright info
$footer_open_table1 = '<table style="text-align: left; width: 100%;" border="0" cellspacing="0" cellpadding="2"><tr><td style="width: 75%; text-align: left; vertical-align: top; font-size: xx-small;">';
// Open the table for the XHTML compliance indicator
$footer_open_table2 = '<td style="width: 25%; text-align: right; vertical-align: top;">';
// Close the table for the copyright info
$footer_close_table1 = '</td>';
// Close the table for the XHTML compliance indicator
$footer_close_table2 = '</td></tr></table>';
?>